# Generated by Django 4.2.3 on 2023-07-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя водителя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
